# Generated by Django 6.0.4 on 2026-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='is_verified_business',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, help_text='Describe your company and what you do'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='employer_logos/'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employee_count',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('500+', '500+ employees')], max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Construction, Technology, Agriculture', max_length=100),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='business_registration',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
