# Generated by Django 6.0.4 on 2026-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='access_code',
            field=models.CharField(blank=True, help_text='Access code or password if needed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact person name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='directions',
            field=models.TextField(blank=True, help_text='Directions for the worker to reach the job site', null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='procedures',
            field=models.TextField(blank=True, help_text='Procedures or instructions for the worker', null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='report_time',
            field=models.DateTimeField(blank=True, help_text='When worker should report to site', null=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for worker to confirm/respond', null=True),
        ),
    ]
