# Generated by Django 6.0.3 on 2026-04-03 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('worker', 'Worker - Looking for jobs'), ('employer', 'Employer - Looking to hire workers'), ('admin', 'Administrator')], default='worker', max_length=10)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('sub_county', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
