"""
Django settings for watukazi_project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g1o$-#80we&n2_f_rd!-g!t-wgu51(+f2g$2_mbkiww6v+i0!0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for django-allauth
    
    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Local apps - Watukazi System
    'home',
    'accounts',
    'workers',
    'employers',
    'jobs',
    'sms_simulator',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    #'accounts.middleware.CreateProfileMiddleware',
    #'sms_simulator.middleware.sms_processor.py'    # Required for django-allauth
]

ROOT_URLCONF = 'watukazi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'notifications.context_processors.notifications_context',
                'accounts.context_processors.sms_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'watukazi_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Using SQLite for development (easy to start with)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For production with MySQL, uncomment the below and comment the above:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'watukazi_db',
#         'USER': 'root',
#         'PASSWORD': 'your_password',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'  # Set to Kenya time

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============ DJANGO-ALLAUTH CONFIGURATION ============

# Site ID for django.contrib.sites
SITE_ID = 1

# Authentication backends
AAUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # 'allauth.account.auth_backends.AuthenticationBackend',  # Comment this out for now
]

# Account settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Set to 'mandatory' for production
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Watukazi] '
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# Email settings (for development - print to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with Gmail, uncomment below:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'

# Login/Logout redirects

# Account adapter


# Login/Logout redirects

LOGOUT_REDIRECT_URL = '/'
# Change LOGIN_URL to point to worker login
LOGIN_URL = '/accounts/worker/login/'

# Also set the redirect URL after login
#LOGIN_REDIRECT_URL = '/'

# ============ CRISPY FORMS CONFIGURATION ============

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ============ SMS CONFIGURATION ============

# SMS Backend (simulated for development)
SMS_BACKEND = 'sms_simulator.backends.ConsoleSMSBackend'

# For production with Africa's Talking API, uncomment below:
# SMS_BACKEND = 'sms_simulator.backends.AfricaTalkingBackend'
# AFRICA_TALKING_USERNAME = 'your_username'
# AFRICA_TALKING_API_KEY = 'your_api_key'
# AFRICA_TALKING_SHORT_CODE = 'your_short_code'

# ============ WATUKAZI CUSTOM SETTINGS ============

# Job matching settings
MINIMUM_SKILL_MATCH_PERCENTAGE = 50  # Minimum 50% skill match for job recommendations
MAX_JOB_MATCHES_PER_REQUEST = 10  # Maximum number of workers to match per job
MAX_JOBS_PER_EMPLOYER = 50  # Maximum active jobs per employer
MAX_APPLICATIONS_PER_WORKER = 20  # Maximum active applications per worker

# Worker availability settings
WORKER_AVAILABILITY_STATUSES = [
    ('available', 'Available for Work'),
    ('busy', 'Currently Busy'),
    ('away', 'Away/Temporarily Unavailable'),
    ('inactive', 'Inactive'),
]

# Job status settings
JOB_STATUSES = [
    ('open', 'Open for Applications'),
    ('matching', 'Matching in Progress'),
    ('matched', 'Workers Matched'),
    ('in_progress', 'Work in Progress'),
    ('completed', 'Completed'),
    ('cancelled', 'Cancelled'),
    ('expired', 'Expired'),
]

# Job match statuses
MATCH_STATUSES = [
    ('pending', 'Pending Worker Response'),
    ('accepted', 'Accepted by Worker'),
    ('rejected', 'Rejected by Worker'),
    ('confirmed', 'Confirmed by Employer'),
    ('started', 'Work Started'),
    ('completed', 'Work Completed'),
    ('cancelled', 'Cancelled'),
]

# Rating settings
MAX_RATING = 5
MIN_RATING = 1
DEFAULT_RATING = 0

# Cache settings (for better performance)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Security settings (for production)
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/watukazi.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'watukazi': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'sms_simulator': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# Message tags for Bootstrap styling
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Custom user model (if needed in the future)
# AUTH_USER_MODEL = 'accounts.CustomUser'

# API settings for future mobile app integration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Africa's Talking SMS API Settings (for production)
# Fill these when deploying to production
AFRICA_TALKING_USERNAME = os.environ.get('AFRICA_TALKING_USERNAME', '')
AFRICA_TALKING_API_KEY = os.environ.get('AFRICA_TALKING_API_KEY', '')
AFRICA_TALKING_SHORT_CODE = os.environ.get('AFRICA_TALKING_SHORT_CODE', '')
AFRICA_TALKING_SENDER_ID = os.environ.get('AFRICA_TALKING_SENDER_ID', 'Watukazi')

# SMS Rate Limiting
SMS_RATE_LIMIT_PER_MINUTE = 10  # Maximum SMS per user per minute
SMS_RATE_LIMIT_PER_DAY = 100  # Maximum SMS per user per day

# Bulk SMS settings
BULK_SMS_BATCH_SIZE = 50  # Number of SMS to send in one batch
BULK_SMS_INTERVAL_SECONDS = 5  # Wait time between batches

# Feature flags (for gradual feature rollout)
FEATURES = {
    'enable_ai_matching': True,
    'enable_sms_notifications': True,
    'enable_email_notifications': True,
    'enable_worker_verification': False,  # Set to True for KYC verification
    'enable_employer_verification': False,
    'enable_rating_system': True,
    'enable_analytics_dashboard': True,
    'enable_mobile_api': False,  # Set to True when building mobile app
}

# Geocoding settings (for location-based matching)
GEOCODING_API_KEY = os.environ.get('GEOCODING_API_KEY', '')
DEFAULT_RADIUS_KM = 10  # Default search radius in kilometers

# Notification settings
NOTIFICATION_SETTINGS = {
    'worker_welcome': True,
    'employer_welcome': True,
    'job_match_found': True,
    'job_application_status': True,
    'job_completion': True,
    'rating_received': True,
    'daily_job_digest': False,  # Send daily summary of available jobs
    'weekly_report': False,  # Send weekly performance report
}

# Pagination settings
PAGINATION_SETTINGS = {
    'JOBS_PER_PAGE': 20,
    'WORKERS_PER_PAGE': 20,
    'MATCHES_PER_PAGE': 15,
    'NOTIFICATIONS_PER_PAGE': 30,
}

# File upload settings
MAX_UPLOAD_SIZE = 5242880  # 5MB in bytes
ALLOWED_UPLOAD_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.pdf', '.doc', '.docx']

# Date and time formats
DATE_FORMAT = 'Y-m-d'
DATETIME_FORMAT = 'Y-m-d H:i:s'
TIME_FORMAT = 'H:i:s'

# Currency settings
CURRENCY_SYMBOL = 'KES'
CURRENCY_CODE = 'KES'
CURRENCY_PLACEMENT = 'before'  # 'before' or 'after'

# Location settings
LOCATION_LEVELS = [
    'county',
    'sub_county',
    'ward',
    'village',
]

# Kenyan Counties list (for validation)
KENYAN_COUNTIES = [
    'Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu', 'Taita Taveta',
    'Garissa', 'Wajir', 'Mandera', 'Marsabit', 'Isiolo', 'Meru', 'Tharaka Nithi',
    'Embu', 'Kitui', 'Machakos', 'Makueni', 'Nyandarua', 'Nyeri', 'Kirinyaga',
    'Muranga', 'Kiambu', 'Turkana', 'West Pokot', 'Samburu', 'Trans Nzoia',
    'Uasin Gishu', 'Elgeyo Marakwet', 'Nandi', 'Baringo', 'Laikipia', 'Nakuru',
    'Narok', 'Kajiado', 'Kericho', 'Bomet', 'Kakamega', 'Vihiga', 'Bungoma',
    'Busia', 'Siaya', 'Kisumu', 'Homa Bay', 'Migori', 'Kisii', 'Nyamira',
    'Nairobi'
]

# Performance monitoring
PERFORMANCE_MONITORING = {
    'enable_metrics': DEBUG,  # Only in debug mode
    'slow_query_threshold_ms': 500,
    'slow_template_threshold_ms': 200,
}

# Emergency contact settings
EMERGENCY_CONTACT = {
    'phone': '0700000000',
    'email': 'emergency@watukazi.co.ke',
    'support_hours': 'Mon-Fri 8:00 AM - 6:00 PM EAT',
}