# Generated by Django 6.0.3 on 2026-04-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Feature image (recommended size: 400x300)', upload_to='feature_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('code_example', models.CharField(blank=True, help_text="Code example like 'JOBS' or 'ADD_SKILL'", max_length=100)),
                ('code_description', models.CharField(blank=True, help_text='Description of the code', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Image',
                'verbose_name_plural': 'Feature Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for this banner', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=200)),
                ('image', models.ImageField(help_text='Banner image (recommended size: 1920x800)', upload_to='hero_banners/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this banner on the homepage')),
                ('link_url', models.CharField(blank=True, help_text='Optional link URL when clicked', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
