# Generated by Django 6.0.3 on 2026-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='workers', to='workers.skill'),
        ),
    ]
