# Generated by Django 6.0.3 on 2026-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_workerprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='id_image',
            field=models.ImageField(blank=True, help_text='Upload your National ID or Passport', null=True, upload_to='worker_ids/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Passport Number', max_length=20),
        ),
    ]
